# Generated by Django 4.2.1 on 2023-06-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
