# Generated by Django 4.1.5 on 2023-02-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='torrent_name_rule',
        ),
        migrations.AddField(
            model_name='website',
            name='torrent_subtitle_rule',
            field=models.CharField(default='.//a[contains(@href,"detail")]/parent::td/text()[last()]', max_length=128, verbose_name='种子标题'),
        ),
        migrations.AlterField(
            model_name='website',
            name='detail_year_publish_rule',
            field=models.CharField(default='//td/b[contains(text(),"发行版年份")]/text()', max_length=128, verbose_name='发行年份'),
        ),
        migrations.AlterField(
            model_name='website',
            name='torrent_title_rule',
            field=models.CharField(default='.//td[@class="embedded"]/a/b/text()', max_length=128, verbose_name='种子名称'),
        ),
    ]
