# Generated by Django 4.2.1 on 2023-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='detail_area_rule',
        ),
        migrations.RemoveField(
            model_name='website',
            name='detail_year_publish_rule',
        ),
        migrations.RemoveField(
            model_name='website',
            name='search_params',
        ),
        migrations.AddField(
            model_name='website',
            name='detail_imdb_rule',
            field=models.CharField(default='//a[@class="faqlink" and starts-with(@href,"https://www.imdb.com/title/")]/@href', max_length=128, verbose_name='IMDB'),
        ),
        migrations.AddField(
            model_name='website',
            name='detail_poster_rule',
            field=models.CharField(default='//td/a/span[contains(text(),"简介")]/parent::a/parent::td/following-sibling::td//img[1]', max_length=128, verbose_name='详情页海报'),
        ),
        migrations.AddField(
            model_name='website',
            name='detail_tags_rule',
            field=models.CharField(default='//td[contains(text(),"标签")]/following-sibling::td//text()', max_length=128, verbose_name='详情页标签'),
        ),
        migrations.AlterField(
            model_name='website',
            name='detail_douban_rule',
            field=models.CharField(default='//td/a[starts-with(@href,"https://movie.douban.com/subject/")][1]', max_length=128, verbose_name='详情页豆瓣信息'),
        ),
        migrations.AlterField(
            model_name='website',
            name='detail_download_url_rule',
            field=models.CharField(default='//td[contains(text(),"种子链接")]/following-sibling::td/a/@href', max_length=128, verbose_name='详情页种子链接'),
        ),
        migrations.AlterField(
            model_name='website',
            name='detail_free_expire_rule',
            field=models.CharField(default='//h1/font/span/@title', max_length=128, verbose_name='详情页促销时间'),
        ),
        migrations.AlterField(
            model_name='website',
            name='detail_free_rule',
            field=models.CharField(default='//h1/b/font/@class', max_length=128, verbose_name='详情页促销标记'),
        ),
    ]
