# Generated by Django 4.2.1 on 2023-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_website_detail_area_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='torrent_tags_rule',
            field=models.CharField(default='.//a[contains(@href,"detail")]/parent::td/br/following::span/@title', max_length=128, verbose_name='种子标签'),
        ),
    ]
