# Generated by Django 4.1.5 on 2023-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0002_remove_website_torrent_name_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='iyuu',
            field=models.IntegerField(default=0, verbose_name='iyuu'),
        ),
    ]
