# Generated by Django 4.1.7 on 2023-04-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_website_iyuu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlevelrule",
            name="rights",
            field=models.TextField(
                default="无", help_text="当前等级所享有的权利与义务", verbose_name="权 利"
            ),
        ),
    ]
