# Generated by Django 4.2.1 on 2023-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_website_torrent_tags_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='detail_hr_rule',
            field=models.CharField(default='//h1/img[@class="hitandrun"]/@title', max_length=128, verbose_name='H&R'),
        ),
    ]
