# Generated by Django 4.1.7 on 2023-04-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_userlevelrule_rights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="tracker",
            field=models.CharField(
                default="",
                help_text="tracker网址关键字",
                max_length=256,
                verbose_name="tracker",
            ),
        ),
    ]
