# Generated by Django 4.2.1 on 2023-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_website_torrent_tags_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='torrent_tags_rule',
            field=models.CharField(default='.//a[contains(@href,"detail")]/../span[contains(@style,"background-color")]/text()', max_length=128, verbose_name='种子标签'),
        ),
    ]
