# Generated by Django 4.1.7 on 2023-05-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_website_func_brush_flow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='func_get_torrents',
            new_name='func_brush_free',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='func_brush_flow',
            new_name='func_brush_rss',
        ),
    ]
