# Generated by Django 4.2.1 on 2023-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_website_torrent_tags_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='torrent_subtitle_rule',
            field=models.CharField(default='.//a[contains(@href,"detail")]/parent::td/text()[last()]', max_length=128, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='website',
            name='torrents_rule',
            field=models.CharField(default='//table[@class="torrents"]/tr', max_length=128, verbose_name='种子列表'),
        ),
    ]
