# Generated by Django 4.2.1 on 2023-09-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_website_torrent_subtitle_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='alive',
            field=models.BooleanField(default=True, help_text='标记站点是否存活！', verbose_name='存活'),
        ),
    ]
