# Generated by Django 4.2.1 on 2023-05-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_func_get_torrents_website_func_brush_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='func_brush_free',
            new_name='brush_free',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='func_brush_rss',
            new_name='brush_rss',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='func_get_userinfo',
            new_name='get_info',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='func_hr_discern',
            new_name='hr_discern',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='func_repeat_torrents',
            new_name='repeat_torrents',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='func_search_torrents',
            new_name='search_torrents',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='func_sign_in',
            new_name='sign_in',
        ),
    ]
