# Generated by Django 4.2.8 on 2024-01-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_website_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='page_pieces_hash_api',
            field=models.CharField(default='api/pieces-hash', max_length=64, verbose_name='Pieces 辅种链接'),
        ),
        migrations.AddField(
            model_name='website',
            name='pieces_repeat',
            field=models.BooleanField(default=False, verbose_name='Pieces辅种'),
        ),
    ]
