# Generated by Django 4.1.5 on 2023-02-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiduOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='百度OCR', editable=False, max_length=64, verbose_name='OCR')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='API-Key')),
                ('secret_key', models.CharField(blank=True, help_text='应用的Secret', max_length=64, null=True, verbose_name='Secret')),
                ('app_id', models.CharField(blank=True, help_text='APP ID', max_length=64, null=True, verbose_name='应用ID')),
            ],
            options={
                'verbose_name': '百度OCR',
                'verbose_name_plural': '百度OCR',
            },
        ),
    ]
