# Generated by Django 4.1.5 on 2023-02-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="baiduocr",
            name="name",
            field=models.CharField(
                default="百度OCR",
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="OCR",
            ),
        ),
    ]
