# Generated by Django 4.1.5 on 2023-02-05 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('category', models.CharField(choices=[('Tr', 'Transmission'), ('Qb', 'qBittorrent')], default='Qb', max_length=128, verbose_name='下载器')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('host', models.CharField(max_length=32, verbose_name='HOST')),
                ('port', models.IntegerField(default=8999, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1001)], verbose_name='端口')),
                ('reserved_space', models.IntegerField(default=30, help_text='单位GB，最小为1G，最大512G', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)], verbose_name='预留磁盘空间')),
            ],
            options={
                'verbose_name': '下载器',
                'verbose_name_plural': '下载器',
            },
        ),
    ]
