# Generated by Django 4.2.1 on 2023-05-29 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('category', models.CharField(choices=[('Tr', 'Transmission'), ('Qb', 'qBittorrent')], default='Qb', max_length=128, verbose_name='下载器')),
                ('http', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=12, verbose_name='协议')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('enable', models.BooleanField(default=True, verbose_name='开启')),
                ('host', models.CharField(max_length=32, verbose_name='HOST')),
                ('port', models.IntegerField(default=8999, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1001)], verbose_name='端口')),
                ('brush', models.BooleanField(default=False, help_text='刷流和保种一定要分开！', verbose_name='刷流专用')),
                ('keep_completed', models.BooleanField(default=False, help_text='可用空间充足时保留已完成的种子!', verbose_name='保留已完成')),
                ('reserved_space', models.IntegerField(default=30, help_text='单位：GB，最小为1G', validators=[django.core.validators.MinValueValidator(1)], verbose_name='预留磁盘空间')),
                ('package_files', models.BooleanField(default=False, verbose_name='自动拆包')),
                ('delete_one_file', models.BooleanField(default=False, help_text='拆包时是否删除单文件的达到拆包标准的种子', verbose_name='删除单文件种子')),
                ('package_size', models.IntegerField(default=5, help_text='单位：GB，大于这个体积才拆包', verbose_name='种子大小')),
                ('package_percent', models.FloatField(default=0.1, help_text='最小0.1，最大0.5', validators=[django.core.validators.MaxValueValidator(0.8), django.core.validators.MinValueValidator(0.1)], verbose_name='拆包大小')),
                ('count_torrents', models.IntegerField(default=0, help_text='刷流时推送种子数量的限制，防止卡IO，0为无限制', verbose_name='种子限制')),
            ],
            options={
                'verbose_name': '下载器',
                'verbose_name_plural': '下载器',
            },
        ),
    ]
