# Generated by Django 4.2.1 on 2023-06-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='repeat',
            field=models.BooleanField(default=False, help_text='刷流和保种一定要分开！', verbose_name='开启辅种'),
        ),
    ]
