# Generated by Django 4.1.7 on 2023-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='开启'),
        ),
    ]
