# Generated by Django 4.1.7 on 2023-05-04 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_downloader_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='delete_one_file',
            field=models.BooleanField(default=False, help_text='拆包时是否删除单文件的达到拆包标准的种子', verbose_name='删除单文件种子'),
        ),
        migrations.AddField(
            model_name='downloader',
            name='package_files',
            field=models.BooleanField(default=False, verbose_name='自动拆包'),
        ),
        migrations.AddField(
            model_name='downloader',
            name='package_percent',
            field=models.FloatField(default=0.1, help_text='最小0.1，最大0.5', validators=[django.core.validators.MaxValueValidator(0.8), django.core.validators.MinValueValidator(0.1)], verbose_name='拆包大小'),
        ),
        migrations.AddField(
            model_name='downloader',
            name='package_size',
            field=models.IntegerField(default=5, help_text='单位：GB，需要拆包的种子大小', verbose_name='种子大小'),
        ),
    ]
