# Generated by Django 4.1.7 on 2023-05-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "download",
            "0003_downloader_delete_one_file_downloader_package_files_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="downloader",
            name="count_torrents",
            field=models.IntegerField(
                default=0, help_text="刷流时推送种子数量的限制，防止卡IO，0为无限制", verbose_name="种子限制"
            ),
        ),
        migrations.AddField(
            model_name="downloader",
            name="http",
            field=models.CharField(
                choices=[("http://", "http://"), ("https://", "https://")],
                default="http://",
                max_length=12,
                verbose_name="协议",
            ),
        ),
    ]
