# Generated by Django 4.2.1 on 2023-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0005_downloader_brush_alter_downloader_package_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloader",
            name="keep_completed",
            field=models.BooleanField(
                default=False, help_text="可用空间充足时保留已完成的种子!", verbose_name="保留已完成"
            ),
        ),
    ]
