# Generated by Django 4.2.1 on 2023-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_downloader_keep_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloader',
            name='http',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=12, verbose_name='协议'),
        ),
    ]
