# Generated by Django 4.1.5 on 2023-02-03 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("sort_id", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "user_id",
                    models.CharField(
                        help_text='请填写<font color="orangered">数字UID</font>，<font color="orange">* az,cz,ez,莫妮卡、普斯特请填写用户名</font>',
                        max_length=16,
                        verbose_name="用户ID",
                    ),
                ),
                (
                    "passkey",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="PassKey"
                    ),
                ),
                (
                    "cookie",
                    models.TextField(
                        help_text="与UA搭配使用效果更佳，请和UA在同一浏览器提取", verbose_name="COOKIE"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        default="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42",
                        help_text="请填写你获取cookie的浏览器的User-Agent",
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "hr",
                    models.BooleanField(
                        default=False, help_text="是否下载HR种子", verbose_name="开启HR下载"
                    ),
                ),
                (
                    "sign_in",
                    models.BooleanField(
                        default=True, help_text="是否开启签到", verbose_name="开启签到"
                    ),
                ),
                (
                    "get_info",
                    models.BooleanField(
                        default=True, help_text="是否抓取站点数据", verbose_name="抓取信息"
                    ),
                ),
                (
                    "search",
                    models.BooleanField(
                        default=True, help_text="是否开启搜索", verbose_name="开启搜索"
                    ),
                ),
                (
                    "time_join",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 1, 1, 12, 30),
                        help_text="请务必填写此项！",
                        verbose_name="注册时间",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.website",
                        verbose_name="站点",
                    ),
                ),
            ],
            options={"verbose_name": "我的站点", "verbose_name_plural": "我的站点",},
        ),
        migrations.CreateModel(
            name="SiteStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("uploaded", models.IntegerField(default=0, verbose_name="上传量")),
                ("downloaded", models.IntegerField(default=0, verbose_name="下载量")),
                ("ratio", models.FloatField(default=0, verbose_name="分享率")),
                ("my_bonus", models.FloatField(default=0, verbose_name="魔力值")),
                ("my_score", models.FloatField(default=0, verbose_name="做种积分")),
                ("seed_volume", models.IntegerField(default=0, verbose_name="做种体积")),
                ("seed_days", models.IntegerField(default=0, verbose_name="做种时间")),
                ("leech", models.IntegerField(default=0, verbose_name="当前下载")),
                ("seed", models.IntegerField(default=0, verbose_name="当前做种")),
                ("bonus_hour", models.FloatField(default=0, verbose_name="时魔")),
                ("publish", models.IntegerField(default=0, verbose_name="发布种子")),
                ("invitation", models.IntegerField(default=0, verbose_name="邀请资格")),
                (
                    "my_level",
                    models.CharField(default="", max_length=16, verbose_name="用户等级"),
                ),
                (
                    "my_hr",
                    models.CharField(default="", max_length=16, verbose_name="H&R"),
                ),
                ("mail", models.IntegerField(default=0, verbose_name="新邮件")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_site.mysite",
                        verbose_name="站点名称",
                    ),
                ),
            ],
            options={"verbose_name": "我的数据", "verbose_name_plural": "我的数据",},
        ),
        migrations.CreateModel(
            name="SignIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sign_in_today",
                    models.BooleanField(default=False, verbose_name="签到"),
                ),
                (
                    "sign_in_info",
                    models.CharField(default="", max_length=256, verbose_name="信息"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_site.mysite",
                        verbose_name="站点名称",
                    ),
                ),
            ],
            options={"verbose_name": "签到", "verbose_name_plural": "签到",},
        ),
    ]
