# Generated by Django 4.2.1 on 2023-05-29 00:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('site', models.IntegerField(unique=True, verbose_name='站点')),
                ('nickname', models.CharField(default=' ', max_length=16, verbose_name='站点昵称')),
                ('sort_id', models.IntegerField(default=1, verbose_name='排序')),
                ('user_id', models.CharField(help_text='请填写<font color="orangered">数字UID</font>，<font color="orange">* az,cz,ez,莫妮卡、普斯特请填写用户名</font>', max_length=16, verbose_name='用户ID')),
                ('passkey', models.CharField(blank=True, max_length=128, null=True, verbose_name='PassKey')),
                ('cookie', models.TextField(help_text='与UA搭配使用效果更佳，请和UA在同一浏览器提取', verbose_name='COOKIE')),
                ('user_agent', models.TextField(default='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42', help_text='请填写你获取cookie的浏览器的User-Agent', verbose_name='User-Agent')),
                ('rss', models.URLField(blank=True, help_text='RSS链接', null=True, verbose_name='RSS地址')),
                ('torrents', models.URLField(blank=True, help_text='免费种子链接', null=True, verbose_name='种子地址')),
                ('sign_in', models.BooleanField(default=True, help_text='是否开启签到', verbose_name='开启签到')),
                ('get_info', models.BooleanField(default=True, help_text='是否抓取站点数据', verbose_name='抓取信息')),
                ('repeat_torrents', models.BooleanField(default=False, verbose_name='辅种支持')),
                ('brush_free', models.BooleanField(default=True, verbose_name='Free刷流')),
                ('brush_rss', models.BooleanField(default=False, help_text='硬刚刷流', verbose_name='RSS刷流')),
                ('package_file', models.BooleanField(default=False, help_text='拆包刷流，只下载一部分，针对大包小硬盘', verbose_name='拆包刷流')),
                ('hr_discern', models.BooleanField(default=False, help_text='是否下载HR种子', verbose_name='开启HR下载')),
                ('search_torrents', models.BooleanField(default=True, help_text='是否开启搜索', verbose_name='开启搜索')),
                ('custom_server', models.URLField(blank=True, help_text='部分站点需要', null=True, verbose_name='代理服务器')),
                ('remove_torrent_rules', models.TextField(blank=True, help_text='详细内容请查看文档', null=True, verbose_name='刷流删种')),
                ('time_join', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 12, 30), help_text='请务必填写此项！', verbose_name='注册时间')),
                ('downloader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.downloader', verbose_name='下载服务器')),
            ],
            options={
                'verbose_name': '我的站点',
                'verbose_name_plural': '我的站点',
                'db_table': 'my_site_mysite',
            },
        ),
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded', models.IntegerField(default=0, verbose_name='上传量')),
                ('downloaded', models.IntegerField(default=0, verbose_name='下载量')),
                ('ratio', models.FloatField(default=0, verbose_name='分享率')),
                ('my_bonus', models.FloatField(default=0, verbose_name='魔力值')),
                ('my_score', models.FloatField(default=0, verbose_name='做种积分')),
                ('seed_volume', models.IntegerField(default=0, verbose_name='做种体积')),
                ('seed_days', models.IntegerField(default=0, verbose_name='做种时间')),
                ('leech', models.IntegerField(default=0, verbose_name='当前下载')),
                ('seed', models.IntegerField(default=0, verbose_name='当前做种')),
                ('bonus_hour', models.FloatField(default=0, verbose_name='时魔')),
                ('publish', models.IntegerField(default=0, verbose_name='发布种子')),
                ('invitation', models.IntegerField(default=0, verbose_name='邀请资格')),
                ('my_level', models.CharField(default='', max_length=16, verbose_name='用户等级')),
                ('my_hr', models.CharField(default='', max_length=32, verbose_name='H&R')),
                ('mail', models.IntegerField(default=0, verbose_name='新邮件')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.mysite', verbose_name='站点名称')),
            ],
            options={
                'verbose_name': '我的数据',
                'verbose_name_plural': '我的数据',
                'db_table': 'my_site_sitestatus',
            },
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sign_in_today', models.BooleanField(default=False, verbose_name='签到')),
                ('sign_in_info', models.TextField(default='', verbose_name='信息')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.mysite', verbose_name='站点名称')),
            ],
            options={
                'verbose_name': '签到',
                'verbose_name_plural': '签到',
                'db_table': 'my_site_signin',
            },
        ),
        migrations.CreateModel(
            name='TorrentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tid', models.IntegerField(verbose_name='种子ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='种子名称')),
                ('subtitle', models.CharField(default='', max_length=256, verbose_name='标题')),
                ('category', models.CharField(default='', max_length=128, verbose_name='分类')),
                ('area', models.CharField(default='', max_length=128, verbose_name='地区')),
                ('magnet_url', models.URLField(default='', verbose_name='下载链接')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('hr', models.BooleanField(default=True, help_text='绿色为通过或无需HR考核', verbose_name='H&R考核')),
                ('sale_status', models.CharField(default='', max_length=16, verbose_name='优惠状态')),
                ('sale_expire', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('seeders', models.IntegerField(default=0, verbose_name='做种人数')),
                ('leechers', models.IntegerField(default=0, verbose_name='下载人数')),
                ('completers', models.IntegerField(default=0, verbose_name='完成人数')),
                ('hash_string', models.CharField(default='', max_length=128, verbose_name='Info_hash')),
                ('filelist', models.CharField(default='', max_length=128, verbose_name='文件列表')),
                ('douban_url', models.URLField(default='', verbose_name='豆瓣链接')),
                ('year_publish', models.CharField(default='', max_length=16, verbose_name='发行年份')),
                ('files_count', models.IntegerField(default=0, verbose_name='文件数目')),
                ('completed', models.IntegerField(default=0, verbose_name='已下载')),
                ('uploaded', models.IntegerField(default=0, verbose_name='已上传')),
                ('pieces_qb', models.CharField(default='', max_length=128, verbose_name='pieces_qb')),
                ('pieces_tr', models.CharField(default='', max_length=128, verbose_name='pieces_tr')),
                ('state', models.IntegerField(default=0, verbose_name='推送状态')),
                ('downloader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.downloader', verbose_name='下载器')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.mysite', to_field='site', verbose_name='所属站点')),
            ],
            options={
                'verbose_name': '种子管理',
                'verbose_name_plural': '种子管理',
                'unique_together': {('site', 'tid')},
            },
        ),
    ]
