# Generated by Django 4.1.5 on 2023-02-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='nickname',
            field=models.CharField(default=' ', max_length=16, verbose_name='站点昵称'),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='site',
            field=models.IntegerField(unique=True, verbose_name='站点'),
        ),
    ]
