# Generated by Django 4.1.5 on 2023-02-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
        ('my_site', '0002_mysite_nickname_alter_mysite_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='', max_length=256, verbose_name='种子名称')),
                ('subtitle', models.CharField(default='', max_length=256, verbose_name='标题')),
                ('category', models.CharField(default='', max_length=128, verbose_name='分类')),
                ('poster_url', models.URLField(default='', max_length=512, verbose_name='海报链接')),
                ('detail_url', models.URLField(default='', max_length=512, verbose_name='种子详情')),
                ('magnet_url', models.URLField(unique=True, verbose_name='下载链接')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('hr', models.BooleanField(default=True, help_text='绿色为通过或无需HR考核', verbose_name='H&R考核')),
                ('sale_status', models.CharField(default='无促销', max_length=16, verbose_name='优惠状态')),
                ('sale_expire', models.CharField(default='无限期', max_length=32, verbose_name='到期时间')),
                ('on_release', models.CharField(default='', max_length=32, verbose_name='发布时间')),
                ('seeders', models.CharField(default='0', max_length=8, verbose_name='做种人数')),
                ('leechers', models.CharField(default='0', max_length=8, verbose_name='下载人数')),
                ('completers', models.CharField(default='0', max_length=8, verbose_name='完成人数')),
                ('hash_string', models.CharField(default='', max_length=128, verbose_name='Info_hash')),
                ('filelist', models.CharField(default='', max_length=128, verbose_name='文件列表')),
                ('douban_url', models.URLField(default='', verbose_name='豆瓣链接')),
                ('year_publish', models.CharField(default='', max_length=16, verbose_name='发行年份')),
                ('files_count', models.IntegerField(default=0, verbose_name='文件数目')),
                ('peer_list_speed', models.FloatField(default=0, max_length=128, verbose_name='平均上传速度')),
                ('save_path', models.FilePathField(default='/downloads/', verbose_name='保存路径')),
                ('state', models.BooleanField(default=False, max_length=16, verbose_name='推送状态')),
                ('downloader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='download.downloader', verbose_name='下载器')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_site.mysite', to_field='site', verbose_name='所属站点')),
            ],
            options={
                'verbose_name': '种子管理',
                'verbose_name_plural': '种子管理',
            },
        ),
    ]
