# Generated by Django 4.2.1 on 2023-06-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0002_alter_torrentinfo_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitestatus",
            name="downloaded",
            field=models.BigIntegerField(default=0, verbose_name="下载量"),
        ),
        migrations.AlterField(
            model_name="sitestatus",
            name="uploaded",
            field=models.BigIntegerField(default=0, verbose_name="上传量"),
        ),
    ]
