# Generated by Django 4.2.1 on 2023-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_alter_sitestatus_downloaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestatus',
            name='my_level',
            field=models.CharField(default='', max_length=32, verbose_name='用户等级'),
        ),
    ]
