# Generated by Django 4.1.7 on 2023-03-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_torrentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestatus',
            name='my_hr',
            field=models.CharField(default='', max_length=32, verbose_name='H&R'),
        ),
    ]
