# Generated by Django 4.2.1 on 2023-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_alter_sitestatus_my_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='torrents',
            field=models.CharField(blank=True, help_text='免费种子链接', max_length=512, null=True, verbose_name='种子地址'),
        ),
    ]
