# Generated by Django 4.1.7 on 2023-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_alter_sitestatus_my_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='brush_flow',
            field=models.BooleanField(default=False, verbose_name='刷流支持'),
        ),
        migrations.AddField(
            model_name='mysite',
            name='get_torrents',
            field=models.BooleanField(default=True, verbose_name='拉取种子'),
        ),
        migrations.AddField(
            model_name='mysite',
            name='repeat_torrents',
            field=models.BooleanField(default=False, verbose_name='辅种支持'),
        ),
    ]
