# Generated by Django 4.1.7 on 2023-05-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0005_mysite_brush_flow_mysite_get_torrents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mysite",
            name="custom_server",
            field=models.URLField(
                blank=True, help_text="部分站点需要", null=True, verbose_name="代理服务器"
            ),
        ),
        migrations.AddField(
            model_name="mysite",
            name="rss",
            field=models.URLField(
                blank=True, help_text="RSS链接", null=True, verbose_name="rss"
            ),
        ),
    ]
