# Generated by Django 4.1.7 on 2023-05-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0002_downloader_enable"),
        ("my_site", "0006_mysite_custom_server_mysite_rss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="torrentinfo", old_name="on_release", new_name="published",
        ),
        migrations.AddField(
            model_name="mysite",
            name="downloader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="download.downloader",
                verbose_name="下载服务器",
            ),
        ),
        migrations.AddField(
            model_name="torrentinfo",
            name="tid",
            field=models.IntegerField(default=0, verbose_name="种子ID"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="torrentinfo", unique_together={("site", "tid")},
        ),
    ]
