# Generated by Django 4.2.1 on 2023-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_mysite_mirror_mysite_mirror_switch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrentinfo',
            name='area',
        ),
        migrations.RemoveField(
            model_name='torrentinfo',
            name='year_publish',
        ),
        migrations.AddField(
            model_name='torrentinfo',
            name='imdb_url',
            field=models.CharField(default='', max_length=128, verbose_name='imdb'),
        ),
        migrations.AddField(
            model_name='torrentinfo',
            name='poster',
            field=models.URLField(default='', verbose_name='海报'),
        ),
        migrations.AddField(
            model_name='torrentinfo',
            name='tags',
            field=models.CharField(default='', max_length=64, verbose_name='种子标签'),
        ),
        migrations.AlterField(
            model_name='torrentinfo',
            name='hash_string',
            field=models.CharField(default='', max_length=128, verbose_name='Info_Hash'),
        ),
    ]
