# Generated by Django 4.1.7 on 2023-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_alter_signin_sign_in_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentinfo',
            name='magnet_url',
            field=models.URLField(default='', verbose_name='下载链接'),
        ),
    ]
