# Generated by Django 4.1.7 on 2023-05-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0009_alter_torrentinfo_magnet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrentinfo',
            name='peer_list_speed',
        ),
        migrations.AddField(
            model_name='torrentinfo',
            name='completed',
            field=models.IntegerField(default=0, verbose_name='已下载'),
        ),
        migrations.AddField(
            model_name='torrentinfo',
            name='pieces_hash',
            field=models.TextField(default='', verbose_name='piece'),
        ),
        migrations.AddField(
            model_name='torrentinfo',
            name='uploaded',
            field=models.IntegerField(default=0, verbose_name='已上传'),
        ),
        migrations.AlterField(
            model_name='torrentinfo',
            name='state',
            field=models.BooleanField(default=False, verbose_name='推送状态'),
        ),
    ]
