# Generated by Django 4.2.8 on 2024-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0010_torrentinfo_pushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='api_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ApiKey'),
        ),
    ]
