# Generated by Django 4.1.7 on 2023-05-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0010_remove_torrentinfo_peer_list_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentinfo',
            name='area',
            field=models.CharField(default='', max_length=128, verbose_name='地区'),
        ),
    ]
