# Generated by Django 4.1.7 on 2023-05-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0011_torrentinfo_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrentinfo',
            name='detail_url',
        ),
        migrations.RemoveField(
            model_name='torrentinfo',
            name='poster_url',
        ),
    ]
