# Generated by Django 4.1.7 on 2023-05-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_remove_torrentinfo_detail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite',
            name='remove_torrent_rules',
            field=models.TextField(blank=True, help_text='详细内容请查看文档', null=True, verbose_name='刷流删种'),
        ),
    ]
