# Generated by Django 4.1.7 on 2023-05-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0014_alter_torrentinfo_sale_expire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysite',
            name='brush_flow',
        ),
        migrations.RemoveField(
            model_name='mysite',
            name='get_torrents',
        ),
        migrations.AddField(
            model_name='mysite',
            name='brush_free',
            field=models.BooleanField(default=True, verbose_name='Free刷流'),
        ),
        migrations.AddField(
            model_name='mysite',
            name='brush_rss',
            field=models.BooleanField(default=False, help_text='硬刚刷流', verbose_name='RSS刷流'),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='rss',
            field=models.URLField(blank=True, help_text='RSS链接/免费种子链接', null=True, verbose_name='刷流地址'),
        ),
    ]
