# Generated by Django 4.2.1 on 2023-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "my_site",
            "0015_remove_mysite_brush_flow_remove_mysite_get_torrents_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mysite",
            name="package_file",
            field=models.BooleanField(
                default=False, help_text="拆包刷流，只下载一部分，针对大包小硬盘", verbose_name="拆包刷流"
            ),
        ),
        migrations.AddField(
            model_name="mysite",
            name="torrents",
            field=models.URLField(
                blank=True, help_text="免费种子链接", null=True, verbose_name="种子地址"
            ),
        ),
        migrations.AlterField(
            model_name="mysite",
            name="rss",
            field=models.URLField(
                blank=True, help_text="RSS链接", null=True, verbose_name="RSS地址"
            ),
        ),
    ]
