# Generated by Django 4.2.1 on 2023-05-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0006_downloader_keep_completed"),
        ("my_site", "0016_mysite_package_file_mysite_torrents_alter_mysite_rss"),
    ]

    operations = [
        migrations.RemoveField(model_name="torrentinfo", name="pieces_hash",),
        migrations.RemoveField(model_name="torrentinfo", name="save_path",),
        migrations.AddField(
            model_name="torrentinfo",
            name="pieces_qb",
            field=models.CharField(
                default="", max_length=128, verbose_name="pieces_qb"
            ),
        ),
        migrations.AddField(
            model_name="torrentinfo",
            name="pieces_tr",
            field=models.CharField(
                default="", max_length=128, verbose_name="pieces_tr"
            ),
        ),
        migrations.AlterField(
            model_name="torrentinfo",
            name="completers",
            field=models.IntegerField(default=0, verbose_name="完成人数"),
        ),
        migrations.AlterField(
            model_name="torrentinfo",
            name="downloader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="download.downloader",
                verbose_name="下载器",
            ),
        ),
        migrations.AlterField(
            model_name="torrentinfo",
            name="leechers",
            field=models.IntegerField(default=0, verbose_name="下载人数"),
        ),
        migrations.AlterField(
            model_name="torrentinfo",
            name="published",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AlterField(
            model_name="torrentinfo",
            name="sale_expire",
            field=models.DateTimeField(blank=True, null=True, verbose_name="到期时间"),
        ),
        migrations.AlterField(
            model_name="torrentinfo",
            name="seeders",
            field=models.IntegerField(default=0, verbose_name="做种人数"),
        ),
        migrations.AlterField(
            model_name="torrentinfo",
            name="state",
            field=models.BooleanField(
                choices=[("未推送", 0), ("已推送", 1), ("已删除", 2)],
                default=0,
                verbose_name="推送状态",
            ),
        ),
    ]
