# Generated by Django 4.2.1 on 2023-05-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0017_remove_torrentinfo_pieces_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysite',
            old_name='hr',
            new_name='hr_discern',
        ),
        migrations.RenameField(
            model_name='mysite',
            old_name='search',
            new_name='search_torrents',
        ),
    ]
