"""
Django settings for auxiliary project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s3y-0-_ma#+ru5#n-j)q(0&zwj4t&q!c6r=f5kl22#ucm@qrt0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "website",
    "my_site",
    "schedule",
    "configuration",
    "monkey",
    "spider",
    "toolbox",
    "download",
    "django_celery_beat",
    "django_celery_results",
    "channels",
]
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auxiliary.middleware.AuthenticateMiddleware",  # 测试阶段先关闭auth认证
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "auxiliary.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "auxiliary.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASE_ROUTERS = ['auxiliary.database_router.DatabaseAppsRouter']

DATABASE_APPS_MAPPING = {
    # 应用名称：对应数据库
    'admin': 'default',
    'auth': 'default',
    'my_site': 'default',
    'website': 'website',
}

mysql_connect = ''
if os.getenv('MYSQL_CONNECTION'):
    mysql_connect = dj_database_url.parse(os.getenv('MYSQL_CONNECTION'))
    mysql_connect.update({
        "CONN_MAX_AGE": 600
    })
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db/data.sqlite3",
        'OPTIONS': {
            'timeout': 120,
            'check_same_thread': False
        },
    } if not os.getenv('MYSQL_CONNECTION') else mysql_connect,
    "website": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "website.sqlite3",
        'OPTIONS': {
            'timeout': 120,
            'check_same_thread': False
        }
    },

}
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('CACHE_REDIS_CONNECTION', f'redis://127.0.0.1:{os.getenv("REDIS_SERVER_PORT")}/15'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {'max_connections': 100},
        },
        'KEY_PREFIX': 'django',
        "DECODE_RESPONSES": True
    }
    # 'default': {
    #     'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
    #     'LOCATION': 'cache_table',  # 数据库表
    #     'TIMEOUT': 600,  # 默认的缓存有效时间,以秒计. 默认值是 300 秒(五分钟).
    #     'OPTIONS': {
    #         'MAX_ENTRIES': 1000  # 缓存的最大条目数(超出该数旧的缓存会被清除,默认值是 300).
    #     }
    # }
}
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(os.path.join(BASE_DIR, 'static')),
)
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 日志配置
LOGGING = {
    'version': 1,  # 版本
    'disable_existing_loggers': False,  # 是否禁用已经存在的日志器
    'formatters': {  # 日志信息显示的格式
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(module)s %(lineno)d %(message)s'
        },
    },
    'filters': {  # 过滤器
        'require_debug_true': {  # django在debug模式下才输出日志
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {  # 日志处理方法
        'console': {  # 向终端中输出日志
            'level': 'DEBUG',  # 输出等级为“INFO”
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {  # 向文件中输出日志
            'level': 'DEBUG',  # 输出等级为“INFO”
            # 新增内容
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/logs.log'),
            'when': 'm',
            'interval': 10,
            'backupCount': 10,
            # 'class': 'logging.handlers.RotatingFileHandler',
            # 'filename': "db/{}.log".format(datetime.datetime.today()),  # 日志文件的位置
            # 'maxBytes': 30 * 1024 * 1024,  # 日志文件的大小（300*1024*1024为300MB）
            # 'backupCount': 10,  # 日志文件的数量（超过设定的最大值会自动备份，备份数量最大值为10）
            'formatter': 'verbose'  # 日志输出格式：使用了在之前定义的'verbose'
        },
    },
    'loggers': {  # 日志器
        'ptools': {  # 定义了一个名为django的日志器
            'handlers': ['console', 'file'],  # 可以同时向终端与文件中输出日志
            'propagate': True,  # 是否继续传递日志信息
            'level': 'DEBUG',  # 日志器接收的最低日志级别
        },
    }
}

# ----Celery redis 配置----- #
# Broker配置，使用Redis作为消息中间件
CELERY_BROKER_URL = os.getenv("CELERY_REDIS_CONNECTION", f'redis://127.0.0.1:{os.getenv("REDIS_SERVER_PORT")}/10')

# BACKEND配置，使用redis
CELERY_RESULT_BACKEND = 'django-db'
# celery切换为同步模式，仅用于代码调试
# CELERY_TASK_EAGER_PROPAGATES_EXCEPTIONS = True
# CELERY_TASK_ALWAYS_EAGER = True

# CELERY_accept_content = ['json']

CELERY_TASK_SERIALIZER = 'json'

CELERY_TASK_TRACK_STARTED = True

CELERY_TASK_TIME_LIMIT = 60 * 60

# 结果序列化方案
CELERY_RESULT_SERIALIZER = 'json'

# 任务结果过期时间，秒
CELERY_RESULT_EXPIRES = 60 * 60 * 24
CELERY_TIMEZONE = "Asia/Shanghai"
# 定时任务数据库配置
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# celery worker 每次去 redis 取任务的数量，默认值就是 4
CELERYD_PREFETCH_MULTIPLIER = 4

# 每个 worker 执行了多少次任务后就会死掉，建议数量大一些
CELERYD_MAX_TASKS_PER_CHILD = 100

#  cors
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8080",
    "http://localhost:8080",
]

# 调整POST传输数据文件大小限制
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
